version: "3"
services:
  nuxt:
    container_name: new-webcv
    build: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - '-c'
      - 'npm i && npm rebuild node-sass && npm run dev'
